//
//  SigninModels.swift
//  thecue
//
//  Created by Benjamin Grima on 01/07/2017.
//  Copyright (c) 2017 Usabilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Signin {
    // MARK: Use cases

    enum LoginWithGoogle {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
