//
//  SigninInteractor.swift
//  thecue
//
//  Created by Benjamin Grima on 01/07/2017.
//  Copyright (c) 2017 Usabilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SigninBusinessLogic {
    func loginWithGoogle(request: Signin.LoginWithGoogle.Request)
}

protocol SigninDataStore {
}

class SigninInteractor: SigninBusinessLogic, SigninDataStore {
    var presenter: SigninPresentationLogic?
    var worker: SigninWorker?

    // MARK: Login with Google

    func loginWithGoogle(request: Signin.LoginWithGoogle.Request) {
        worker = SigninWorker()
        worker?.loginWithGoogle { [unowned self] in
            let response = Signin.LoginWithGoogle.Response()
            self.presenter?.presentLogin(response: response)
        }
    }
}
