//
//  LobbyRouter.swift
//  thecue
//
//  Created by Benjamin Grima on 02/07/2017.
//  Copyright (c) 2017 Usabilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LobbyRoutingLogic { }

protocol LobbyDataPassing {
    var dataStore: LobbyDataStore? { get }
}

class LobbyRouter: NSObject, LobbyRoutingLogic, LobbyDataPassing {
    weak var viewController: LobbyViewController?
    var dataStore: LobbyDataStore?
}
