//
//  LobbyModels.swift
//  thecue
//
//  Created by Benjamin Grima on 02/07/2017.
//  Copyright (c) 2017 Usabilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Lobby {
    // MARK: Use cases

    enum FetchTables {
        struct Request {
        }
        struct Response {
            var tables: [Table]
        }
        struct ViewModel {
            var tables: [Table] = []
        }
    }

    enum FetchTableGames {

        struct Request {
            var queueName: String
        }
        struct Response {
            var items: [LobbyItem]
        }
        struct ViewModel {
            struct DisplayedGame {
                var name: String
            }
            var displayedGames: [DisplayedGame]
            var isInTheQueue: Bool
        }
    }

    enum CreateTableGame {
        struct Request {
            var queueName: String
        }
        struct Response {

        }
        struct ViewModel {
        }
    }

    enum DeleteTableGame {
        struct Request {
            var queueName: String
        }
        struct Response {

        }
        struct ViewModel {
        }
    }
}
