//
//  LobbyPresenter.swift
//  thecue
//
//  Created by Benjamin Grima on 02/07/2017.
//  Copyright (c) 2017 Usabilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol LobbyPresentationLogic {
    func presentTables(response: Lobby.FetchTables.Response)
    func presentTableGames(response: Lobby.FetchTableGames.Response)
}

class LobbyPresenter: LobbyPresentationLogic {
    weak var viewController: LobbyDisplayLogic?

    // MARK: user cases

    func presentTables(response: Lobby.FetchTables.Response) {
        let viewModel = Lobby.FetchTables.ViewModel(tables: response.tables)
        viewController?.displayTables(viewModel: viewModel)
    }

    func presentTableGames(response: Lobby.FetchTableGames.Response) {
        let alreadyQueuing = response.items.first { $0.userId == Auth.auth().currentUser!.providerData[0].uid } != nil
        let displayedGames = response.items.map { Lobby.FetchTableGames.ViewModel.DisplayedGame(name: $0.name) }
        let viewModel = Lobby.FetchTableGames.ViewModel(displayedGames: displayedGames, isInTheQueue: alreadyQueuing)
        viewController?.displayTableGames(viewModel: viewModel)
    }
}
